In [32]:
import pandas as pd
import numpy as np

from catboost import CatBoostClassifier

from sklearn.model_selection import train_test_split

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    confusion_matrix,
    classification_report
)

import joblib
import matplotlib.pyplot as plt

In [33]:
df = pd.read_csv("../Dataset/final_dataset.csv")

df.head()

,code_module,code_presentation,gender,region,highest_education,imd_band,age_band,num_of_prev_attempts,studied_credits,disability,final_result,dropout,avg_quiz_score,assessments_completed,avg_assessment_weight,avg_submission_day,video_clicks,login_frequency,avg_activity_day,registration_days
0,AAA,2013J,M,East Anglian Region,HE Qualification,90-100%,55<=,0,240,N,Pass,0,78.0,1.0,10.0,18.0,934.0,196.0,102.132653,270.0
1,AAA,2013J,F,Scotland,HE Qualification,20-30%,35-55,0,60,N,Pass,0,70.0,1.0,10.0,22.0,1435.0,430.0,86.993023,270.0
2,AAA,2013J,F,North Western Region,A Level or Equivalent,30-40%,35-55,0,60,Y,Withdrawn,1,0.0,0.0,0.0,0.0,281.0,76.0,2.355263,104.0
3,AAA,2013J,F,South East Region,A Level or Equivalent,50-60%,35-55,0,60,N,Pass,0,72.0,1.0,10.0,17.0,2158.0,663.0,106.147813,270.0
4,AAA,2013J,F,West Midlands Region,Lower Than A Level,50-60%,0-35,0,60,N,Pass,0,69.0,1.0,10.0,26.0,1034.0,352.0,91.934659,270.0

In [34]:
print(df.shape)

df.info()

(32593, 20)
<class 'pandas.DataFrame'>
RangeIndex: 32593 entries, 0 to 32592
Data columns (total 20 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   code_module            32593 non-null  str
 1   code_presentation      32593 non-null  str
 2   gender                 32593 non-null  str
 3   region                 32593 non-null  str
 4   highest_education      32593 non-null  str
 5   imd_band               32593 non-null  str
 6   age_band               32593 non-null  str
 7   num_of_prev_attempts   32593 non-null  int64
 8   studied_credits        32593 non-null  int64
 9   disability             32593 non-null  str
 10  final_result           32593 non-null  str
 11  dropout                32593 non-null  int64
 12  avg_quiz_score         32593 non-null  float64
 13  assessments_completed  32593 non-null  float64
 14  avg_assessment_weight  32593 non-null  float64
 15  avg_submission_day     32593 non-null  float64
 16  video_clicks           32593 non-null  float64
 17  login_frequency        32593 non-null  float64
 18  avg_activity_day       32593 non-null  float64
 19  registration_days      32593 non-null  float64
dtypes: float64(8), int64(3), str(9)
memory usage: 5.0 MB

In [35]:
# Remove Unwanted Columns
if "final_result" in df.columns:
    df = df.drop(columns=["final_result"])

df.head()

,code_module,code_presentation,gender,region,highest_education,imd_band,age_band,num_of_prev_attempts,studied_credits,disability,dropout,avg_quiz_score,assessments_completed,avg_assessment_weight,avg_submission_day,video_clicks,login_frequency,avg_activity_day,registration_days
0,AAA,2013J,M,East Anglian Region,HE Qualification,90-100%,55<=,0,240,N,0,78.0,1.0,10.0,18.0,934.0,196.0,102.132653,270.0
1,AAA,2013J,F,Scotland,HE Qualification,20-30%,35-55,0,60,N,0,70.0,1.0,10.0,22.0,1435.0,430.0,86.993023,270.0
2,AAA,2013J,F,North Western Region,A Level or Equivalent,30-40%,35-55,0,60,Y,1,0.0,0.0,0.0,0.0,281.0,76.0,2.355263,104.0
3,AAA,2013J,F,South East Region,A Level or Equivalent,50-60%,35-55,0,60,N,0,72.0,1.0,10.0,17.0,2158.0,663.0,106.147813,270.0
4,AAA,2013J,F,West Midlands Region,Lower Than A Level,50-60%,0-35,0,60,N,0,69.0,1.0,10.0,26.0,1034.0,352.0,91.934659,270.0

In [36]:
# Separate Features and Target
X = df.drop(
    columns=[
        "dropout",
        "registration_days"
    ],
    errors="ignore"
)
y = df["dropout"]

In [37]:
# Identify Categorical Columns
categorical_features = X.select_dtypes(
    include=["object"]
).columns.tolist()

print(categorical_features)

['code_module', 'code_presentation', 'gender', 'region', 'highest_education', 'imd_band', 'age_band', 'disability']

C:\Users\saran\AppData\Local\Temp\ipykernel_12888\2416283405.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_features = X.select_dtypes(

In [38]:
# Train-Test Split
X_train, X_test, y_train, y_test = train_test_split(

    X,
    y,

    test_size=0.2,

    random_state=42,

    stratify=y

)

In [39]:
df["dropout"].value_counts()

dropout
0    22437
1    10156
Name: count, dtype: int64

In [40]:
df = pd.read_csv("../Dataset/final_dataset.csv")

print(df["dropout"].value_counts())

dropout
0    22437
1    10156
Name: count, dtype: int64

In [41]:
df["dropout"].value_counts()
df.head()
import pandas as pd

studentInfo = pd.read_csv("../Dataset/processed/studentInfo_clean.csv")

studentInfo["final_result"].value_counts()
studentInfo["final_result"].unique()

<StringArray>
['Pass', 'Withdrawn', 'Fail', 'Distinction']
Length: 4, dtype: str

In [42]:
studentInfo["final_result"].value_counts()

final_result
Pass           12361
Withdrawn      10156
Fail            7052
Distinction     3024
Name: count, dtype: int64

In [43]:
# Train CatBoost Model
model = CatBoostClassifier(

    iterations=500,

    learning_rate=0.05,

    depth=6,

    loss_function="Logloss",

    eval_metric="AUC",

    verbose=100,

    random_seed=42

)

model.fit(

    X_train,

    y_train,

    cat_features=categorical_features

)

0:	total: 106ms	remaining: 53.1s
100:	total: 8.62s	remaining: 34.1s
200:	total: 16.6s	remaining: 24.7s
300:	total: 24.5s	remaining: 16.2s
400:	total: 32.5s	remaining: 8.02s
499:	total: 40.3s	remaining: 0us

CatBoostClassifier(depth=6, eval_metric='AUC', iterations=500, learning_rate=0.05, loss_function='Logloss', random_seed=42, verbose=100)

In [44]:
# Prediction
y_pred = model.predict(X_test)

y_prob = model.predict_proba(X_test)[:,1]

In [45]:
# Accuracy
accuracy = accuracy_score(y_test,y_pred)

print("Accuracy :",accuracy)

Accuracy : 0.8671575394999232

In [46]:
print("Accuracy :", accuracy_score(y_test, y_pred))
print("Precision :", precision_score(y_test, y_pred))
print("Recall :", recall_score(y_test, y_pred))
print("F1 Score :", f1_score(y_test, y_pred))
print("ROC AUC :", roc_auc_score(y_test, y_prob))

print("\nConfusion Matrix")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report")
print(classification_report(y_test, y_pred))

Accuracy : 0.8671575394999232
Precision : 0.7834549878345499
Recall : 0.792712949286066
F1 Score : 0.7880567792462065
ROC AUC : 0.941295503475102

Confusion Matrix
[[4043  445]
 [ 421 1610]]

Classification Report
              precision    recall  f1-score   support

           0       0.91      0.90      0.90      4488
           1       0.78      0.79      0.79      2031

    accuracy                           0.87      6519
   macro avg       0.84      0.85      0.85      6519
weighted avg       0.87      0.87      0.87      6519

In [47]:
print(df["dropout"].value_counts())
print(df["dropout"].value_counts(normalize=True))

dropout
0    22437
1    10156
Name: count, dtype: int64
dropout
0    0.688399
1    0.311601
Name: proportion, dtype: float64

In [48]:
print(X.columns.tolist())

['code_module', 'code_presentation', 'gender', 'region', 'highest_education', 'imd_band', 'age_band', 'num_of_prev_attempts', 'studied_credits', 'disability', 'avg_quiz_score', 'assessments_completed', 'avg_assessment_weight', 'avg_submission_day', 'video_clicks', 'login_frequency', 'avg_activity_day']

In [49]:
train_pred = model.predict(X_train)
test_pred = model.predict(X_test)

from sklearn.metrics import accuracy_score

print("Training Accuracy :", accuracy_score(y_train, train_pred))
print("Testing Accuracy  :", accuracy_score(y_test, test_pred))

Training Accuracy : 0.883945693027537
Testing Accuracy  : 0.8671575394999232

In [50]:
importance = pd.DataFrame({
    "Feature": X.columns,
    "Importance": model.get_feature_importance()
})

importance = importance.sort_values(
    by="Importance",
    ascending=False
)

print(importance)

                  Feature  Importance
16       avg_activity_day   50.334664
0             code_module    6.685163
14           video_clicks    5.954141
15        login_frequency    5.097605
13     avg_submission_day    4.117417
1       code_presentation    3.917573
3                  region    3.899627
10         avg_quiz_score    3.890741
8         studied_credits    3.757079
5                imd_band    2.075968
12  avg_assessment_weight    1.869501
2                  gender    1.781217
4       highest_education    1.608536
7    num_of_prev_attempts    1.511563
6                age_band    1.435188
11  assessments_completed    1.236651
9              disability    0.827367