In [1]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import NearestNeighbors

import joblib

In [2]:
df = pd.read_csv("../Dataset/student_risk_prediction.csv")

df.head()

,Student ID,avg_activity_day,login_frequency,video_clicks,avg_quiz_score,avg_submission_day,assessments_completed,avg_assessment_weight,studied_credits,code_module,...,highest_education,age_band,engagement_score,activity_per_login,quiz_completion,submission_consistency,Actual,Predicted,Risk Probability,Risk Level
0,1,102.132653,196.0,934.0,78.0,18.0,1.0,10.0,240,AAA,...,HE Qualification,55<=,410.710884,4.741117,78.0,9.0,0,0,0.018977,Low
1,2,86.993023,430.0,1435.0,70.0,22.0,1.0,10.0,60,AAA,...,HE Qualification,35-55,650.664341,3.329466,70.0,11.0,0,0,0.059905,Low
2,3,2.355263,76.0,281.0,0.0,0.0,0.0,0.0,60,AAA,...,A Level or Equivalent,35-55,119.785088,3.649351,0.0,0.0,1,1,0.691936,Medium
3,4,106.147813,663.0,2158.0,72.0,17.0,1.0,10.0,60,AAA,...,A Level or Equivalent,35-55,975.715938,3.250000,72.0,8.5,0,0,0.007632,Low
4,5,91.934659,352.0,1034.0,69.0,26.0,1.0,10.0,60,AAA,...,Lower Than A Level,0-35,492.644886,2.929178,69.0,13.0,0,0,0.042361,Low

In [3]:
features = [
    "avg_activity_day",
    "login_frequency",
    "video_clicks",
    "avg_quiz_score",
    "avg_submission_day",
    "assessments_completed",
    "avg_assessment_weight",
    "studied_credits"
]

X = df[features]

In [4]:
# Normalize Data
scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

print(X_scaled.shape)

(32593, 8)

In [5]:
# Train KNN Model
knn = NearestNeighbors(
    n_neighbors=5,
    metric="euclidean"
)

knn.fit(X_scaled)

print("KNN Model Trained Successfully")

KNN Model Trained Successfully

In [6]:
# save the KNN model
joblib.dump(knn,"../backend/models/knn_model.pkl")

joblib.dump(scaler,"../backend/models/knn_scaler.pkl")

print("Model Saved")

Model Saved

In [7]:
# Find Similar Students
student_index = 50

distance, indices = knn.kneighbors(
    [X_scaled[student_index]]
)

print(indices)

[[   50   368   727 14916    67]]

In [8]:
# Show Similar Students
similar_students = df.iloc[indices[0]]

similar_students

,Student ID,avg_activity_day,login_frequency,video_clicks,avg_quiz_score,avg_submission_day,assessments_completed,avg_assessment_weight,studied_credits,code_module,...,highest_education,age_band,engagement_score,activity_per_login,quiz_completion,submission_consistency,Actual,Predicted,Risk Probability,Risk Level
50,51,127.147531,1620.0,5645.0,61.0,19.0,1.0,10.0,60,AAA,...,HE Qualification,35-55,2464.049177,3.482418,61.0,9.5,0,0,0.005356,Low
368,369,132.238796,1562.0,5974.0,75.0,14.0,1.0,10.0,60,AAA,...,Lower Than A Level,35-55,2556.079599,3.822137,75.0,7.0,0,0,0.003976,Low
727,728,108.899427,1571.0,5956.0,56.0,24.0,1.0,10.0,60,AAA,...,Lower Than A Level,35-55,2545.299809,3.788804,56.0,12.0,0,0,0.008515,Low
14916,14917,112.741082,1626.0,5612.0,49.0,25.0,1.0,10.0,60,DDD,...,Lower Than A Level,35-55,2450.247027,3.449293,49.0,12.5,0,0,0.018126,Low
67,68,116.346318,1643.0,6318.0,83.0,17.0,1.0,10.0,60,AAA,...,HE Qualification,55<=,2692.448773,3.843066,83.0,8.5,0,0,0.004904,Low

In [9]:
def recommend_resources(student_index):

    distances, indices = knn.kneighbors(
        [X_scaled[student_index]]
    )

    student = df.iloc[student_index]

    similar_students = df.iloc[indices[0]]

    recommendations = []

    # Risk based recommendations
    if student["Risk Level"] == "High":

        recommendations.extend([
            "Complete all pending assignments",
            "Watch all remaining video lectures",
            "Practice additional quizzes",
            "Login every day",
            "Attend mentor support session"
        ])

    elif student["Risk Level"] == "Medium":

        recommendations.extend([
            "Complete practice quizzes",
            "Increase weekly login frequency",
            "Participate in discussion forums"
        ])

    else:

        recommendations.extend([
            "Continue current learning schedule",
            "Attempt advanced quizzes",
            "Revise completed modules"
        ])

    # Compare with similar students

    avg_quiz = similar_students["avg_quiz_score"].mean()

    avg_video = similar_students["video_clicks"].mean()

    avg_login = similar_students["login_frequency"].mean()

    if student["avg_quiz_score"] < avg_quiz:
        recommendations.append(
            "Improve quiz performance to match similar students."
        )

    if student["video_clicks"] < avg_video:
        recommendations.append(
            "Watch more course videos."
        )

    if student["login_frequency"] < avg_login:
        recommendations.append(
            "Increase login frequency."
        )

    return recommendations, similar_students

In [10]:
recommendations, similar_students = recommend_resources(100)

print("Risk Level :", df.iloc[100]["Risk Level"])

print("\nRecommendations")

for r in recommendations:

    print("✔", r)

Risk Level : Low

Recommendations
✔ Continue current learning schedule
✔ Attempt advanced quizzes
✔ Revise completed modules
✔ Improve quiz performance to match similar students.
✔ Watch more course videos.

In [11]:
print("\nSimilar Students")

similar_students[[
    "avg_quiz_score",
    "video_clicks",
    "login_frequency",
    "Risk Level"
]]

Similar Students

       avg_quiz_score  video_clicks  login_frequency Risk Level
100              51.0        1829.0            627.0        Low
65               60.0        1939.0            697.0        Low
304              56.0        1588.0            544.0        Low
15218            61.0        1709.0            610.0        Low
49               65.0        2121.0            631.0        Low

In [12]:
recommendations, similar_students = recommend_resources(200)

print("Risk Level :", df.iloc[200]["Risk Level"])

for r in recommendations:
    print("✔", r)

Risk Level : High
✔ Complete all pending assignments
✔ Watch all remaining video lectures
✔ Practice additional quizzes
✔ Login every day
✔ Attend mentor support session
✔ Improve quiz performance to match similar students.

In [13]:
recommendation_list = []

for i in range(len(df)):

    rec, _ = recommend_resources(i)

    recommendation_list.append(", ".join(rec))

df["Recommendation"] = recommendation_list

df.to_csv(
    "../Dataset/student_recommendation.csv",
    index=False
)

print("Student Recommendation Dataset Saved Successfully")

Student Recommendation Dataset Saved Successfully